import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import {
  ProviderId,
  CustomModel,
  Project,
  ChatSession,
  Agent,
  UsageLog,
  UserSettings,
  UserProviderKey
} from '../src/types/index.js';
import { encryptApiKey, decryptApiKey, maskApiKey } from './security.js';

interface StoredEncryptedKey {
  providerId: ProviderId;
  encryptedKey: string;
  status: 'connected' | 'not_connected' | 'error';
  lastTestedAt?: string;
  errorMessage?: string;
  customBaseUrl?: string;
  customProviderName?: string;
}

interface UserData {
  userId: string;
  keys: Record<string, StoredEncryptedKey>;
  models: CustomModel[];
  projects: Project[];
  chats: ChatSession[];
  agents: Agent[];
  usage: UsageLog[];
  settings: UserSettings;
}

const STORAGE_FILE = path.resolve(process.cwd(), '.aura_storage.json');

class AuraStorage {
  private data: Record<string, UserData> = {};

  constructor() {
    this.load();
  }

  private load() {
    try {
      if (fs.existsSync(STORAGE_FILE)) {
        const raw = fs.readFileSync(STORAGE_FILE, 'utf-8');
        this.data = JSON.parse(raw);
      }
    } catch {
      this.data = {};
    }
  }

  private save() {
    try {
      fs.writeFileSync(STORAGE_FILE, JSON.stringify(this.data, null, 2), 'utf-8');
    } catch (err) {
      console.error('Failed to save aura storage file');
    }
  }

  getUser(userId: string): UserData {
    if (!this.data[userId]) {
      this.data[userId] = {
        userId,
        keys: {},
        models: [
          {
            id: 'mod_gemini_flash',
            userId,
            providerId: 'gemini',
            modelName: 'Gemini 3.8 Flash (Default)',
            modelId: 'gemini-3.8-flash',
            description: 'Next-gen frontier reasoning & massive speed',
            contextLength: 1048576,
            inputPrice: 0.15,
            outputPrice: 0.60,
            capabilities: {
              text: true,
              vision: true,
              image: false,
              audio: true,
              toolCalling: true,
              structuredOutput: true
            },
            isFixed: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
          },
          {
            id: 'mod_openai_gpt4o',
            userId,
            providerId: 'openai',
            modelName: 'GPT-4o Mini',
            modelId: 'gpt-4o-mini',
            description: 'Fast coding and text processing',
            contextLength: 128000,
            inputPrice: 0.15,
            outputPrice: 0.60,
            capabilities: {
              text: true,
              vision: true,
              image: false,
              audio: false,
              toolCalling: true,
              structuredOutput: true
            },
            isFixed: false,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString()
          }
        ],
        projects: [
          {
            id: 'proj_starter_1',
            name: 'AURA Web Demo App',
            description: 'A responsive developer dashboard built with HTML, Tailwind CSS and JavaScript',
            userId,
            templateType: 'web',
            activeFilePath: 'index.html',
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            files: [
              {
                path: 'index.html',
                language: 'html',
                updatedAt: new Date().toISOString(),
                content: `<!DOCTYPE html>
<html lang="ja" class="dark">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>AURA Interactive Prototype</title>
  <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
</head>
<body class="bg-slate-950 text-slate-100 min-h-screen p-8 flex flex-col items-center justify-center font-sans">
  <div class="max-w-xl w-full bg-slate-900 border border-slate-800 rounded-2xl p-8 shadow-2xl space-y-6">
    <div class="flex items-center space-x-3">
      <div class="w-10 h-10 rounded-xl bg-gradient-to-tr from-cyan-500 to-indigo-500 flex items-center justify-center font-bold text-white shadow-lg shadow-indigo-500/30">
        ⚡
      </div>
      <div>
        <h1 class="text-xl font-bold tracking-tight">Generated by AURA DEV</h1>
        <p class="text-xs text-slate-400">Bring Your Own Key &amp; Model Workspace</p>
      </div>
    </div>
    <p class="text-sm text-slate-300 leading-relaxed">
      このアプリケーションはAURA DEVのコード生成・プレビュー機能で稼働しています。AIエディタから自由にプロンプトを送信し、ファイルを更新できます。
    </p>
    <div class="grid grid-cols-2 gap-4">
      <div class="p-4 bg-slate-800/60 rounded-xl border border-slate-700/50">
        <span class="text-xs text-slate-400 block mb-1">Status</span>
        <span class="text-sm font-semibold text-emerald-400">● Live Preview Active</span>
      </div>
      <div class="p-4 bg-slate-800/60 rounded-xl border border-slate-700/50">
        <span class="text-xs text-slate-400 block mb-1">Architecture</span>
        <span class="text-sm font-semibold text-indigo-300">Single File HTML/JS</span>
      </div>
    </div>
    <button onclick="changeColor()" class="w-full py-3 bg-indigo-600 hover:bg-indigo-500 text-white font-medium rounded-xl transition shadow-lg shadow-indigo-600/30 cursor-pointer">
      クリックしてインタラクションテスト
    </button>
    <div id="counterBox" class="text-center text-xs text-slate-400 font-mono">
      Clicks: <span id="clickCount" class="text-indigo-400 font-bold">0</span>
    </div>
  </div>

  <script>
    let clicks = 0;
    function changeColor() {
      clicks++;
      document.getElementById('clickCount').innerText = clicks;
      const colors = ['#6366f1', '#06b6d4', '#10b981', '#f59e0b', '#ec4899'];
      const chosen = colors[clicks % colors.length];
      document.getElementById('clickCount').style.color = chosen;
    }
  </script>
</body>
</html>`
              },
              {
                path: 'README.md',
                language: 'markdown',
                updatedAt: new Date().toISOString(),
                content: `# AURA Web Demo App\n\nGenerated with AURA DEV Build Mode.\n\n## Features\n- Live Sandboxed Preview\n- Responsive Tailwind CSS\n- Real-time AI Code Editing with Diff Viewer`
              }
            ]
          }
        ],
        chats: [
          {
            id: 'chat_welcome',
            userId,
            title: 'AURA DEV へようこそ',
            providerId: 'gemini',
            modelId: 'gemini-2.5-flash',
            modelName: 'Gemini 2.5 Flash (Default)',
            totalInputTokens: 120,
            totalOutputTokens: 240,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            messages: [
              {
                id: 'm1',
                role: 'user',
                content: 'AURA DEV の特徴を教えてください。',
                timestamp: new Date(Date.now() - 60000).toISOString()
              },
              {
                id: 'm2',
                role: 'assistant',
                content: `### AURA DEV へようこそ！\n\nAURA DEV は**「自分のAPIキーで、自分専用のAI開発環境を作る」**ための本格的なAI開発プラットフォームです。\n\n#### 🎯 主なコア機能\n1. **Bring Your Own Key (BYOK)**: ユーザー自身のAPIキーを安全に暗号化保持。プラットフォーム側でAPI利用料を請求することなく、各プロバイダーの公式料金で直接利用できます。\n2. **自由な Model ID 登録 (BYOM)**: プロバイダーが提供するモデル一覧からの選択だけでなく、未登録の最新モデルやカスタムModel IDを直接指定可能。\n3. **🔒 固定モデル (Fixed Model)**: 勝手にAIがモデルを変更しないよう固定ロック。\n4. **🛠️ Build Mode & コード編集**: 自然言語からWebプロジェクトを自動生成し、Diff Viewerでビジュアル差分確認＆適用。\n5. **🤖 AI Agents**: Web検索やファイル読み書きツールを備えた専用エージェントの作成。\n\nまずは左メニューの「API Keys」からお好みのプロバイダーを接続してください！`,
                timestamp: new Date().toISOString(),
                modelName: 'Gemini 2.5 Flash',
                modelId: 'gemini-2.5-flash'
              }
            ]
          }
        ],
        agents: [
          {
            id: 'ag_fullstack',
            userId,
            name: 'Full-Stack Web Architect',
            description: 'Autonomous coding agent specialized in clean HTML/TS/React architecture and bug fixes',
            systemPrompt: 'You are an expert senior full-stack developer. Write clean, accessible, modern web applications. Prioritize maintainability, responsive layouts, and defensive coding.',
            providerId: 'gemini',
            modelId: 'gemini-2.5-flash',
            temperature: 0.3,
            maxTokens: 4096,
            memoryEnabled: true,
            createdAt: new Date().toISOString(),
            updatedAt: new Date().toISOString(),
            tools: [
              { id: 'web_search', name: 'Web Search', description: 'Search latest documentation and npm packages', enabled: true, requiresConfirmation: false },
              { id: 'file_read', name: 'File Read', description: 'Read workspace files', enabled: true, requiresConfirmation: false },
              { id: 'file_write', name: 'File Write', description: 'Propose or write file changes to workspace', enabled: true, requiresConfirmation: true },
              { id: 'code_gen', name: 'Code Generation', description: 'Synthesize new full stack components', enabled: true, requiresConfirmation: false }
            ]
          }
        ],
        usage: [
          {
            id: 'us_init_1',
            userId,
            timestamp: new Date().toISOString(),
            providerId: 'gemini',
            modelId: 'gemini-2.5-flash',
            modelName: 'Gemini 2.5 Flash',
            action: 'chat',
            inputTokens: 120,
            outputTokens: 240,
            totalTokens: 360,
            estimatedCost: 0.00016,
            status: 'success'
          }
        ],
        settings: {
          theme: 'dark',
          autoMode: false,
          allowedProvidersForAuto: ['gemini', 'openrouter'],
          isDemoMode: false
        }
      };
      this.save();
    }
    return this.data[userId];
  }

  // Keys management
  getMaskedKeys(userId: string): UserProviderKey[] {
    const user = this.getUser(userId);
    return Object.values(user.keys).map(k => ({
      providerId: k.providerId,
      maskedKey: maskApiKey(decryptApiKey(k.encryptedKey)),
      status: k.status,
      lastTestedAt: k.lastTestedAt,
      errorMessage: k.errorMessage,
      customBaseUrl: k.customBaseUrl,
      customProviderName: k.customProviderName
    }));
  }

  getRawApiKey(userId: string, providerId: ProviderId): { apiKey: string; customBaseUrl?: string } | null {
    const user = this.getUser(userId);
    const item = user.keys[providerId];
    if (!item) return null;
    const rawKey = decryptApiKey(item.encryptedKey);
    return {
      apiKey: rawKey,
      customBaseUrl: item.customBaseUrl
    };
  }

  setApiKey(
    userId: string,
    providerId: ProviderId,
    plainKey: string,
    status: 'connected' | 'not_connected' | 'error',
    customBaseUrl?: string,
    customProviderName?: string,
    errorMessage?: string
  ) {
    const user = this.getUser(userId);
    const encryptedKey = encryptApiKey(plainKey.trim());
    user.keys[providerId] = {
      providerId,
      encryptedKey,
      status,
      lastTestedAt: new Date().toISOString(),
      errorMessage,
      customBaseUrl,
      customProviderName
    };
    this.save();
  }

  removeApiKey(userId: string, providerId: ProviderId) {
    const user = this.getUser(userId);
    delete user.keys[providerId];
    this.save();
  }

  // Models management
  getModels(userId: string): CustomModel[] {
    const user = this.getUser(userId);
    return user.models;
  }

  saveModel(userId: string, model: Omit<CustomModel, 'id' | 'createdAt' | 'updatedAt' | 'userId'> & { id?: string }): CustomModel {
    const user = this.getUser(userId);
    const now = new Date().toISOString();

    if (model.isFixed) {
      // Unset previous fixed
      user.models.forEach(m => { m.isFixed = false; });
    }

    if (model.id) {
      const idx = user.models.findIndex(m => m.id === model.id);
      if (idx !== -1) {
        user.models[idx] = {
          ...user.models[idx],
          ...model,
          userId,
          updatedAt: now
        };
        this.save();
        return user.models[idx];
      }
    }

    const newModel: CustomModel = {
      id: `mod_${crypto.randomUUID().slice(0, 8)}`,
      userId,
      providerId: model.providerId,
      modelName: model.modelName.trim(),
      modelId: model.modelId.trim(),
      description: model.description || '',
      contextLength: model.contextLength,
      inputPrice: model.inputPrice,
      outputPrice: model.outputPrice,
      capabilities: model.capabilities || { text: true, vision: false, image: false, audio: false, toolCalling: false, structuredOutput: false },
      isFixed: !!model.isFixed,
      createdAt: now,
      updatedAt: now,
      isCustomProvider: model.isCustomProvider,
      customBaseUrl: model.customBaseUrl
    };

    user.models.unshift(newModel);
    this.save();
    return newModel;
  }

  setFixedModel(userId: string, modelId: string): boolean {
    const user = this.getUser(userId);
    let found = false;
    user.models.forEach(m => {
      if (m.id === modelId) {
        m.isFixed = true;
        found = true;
      } else {
        m.isFixed = false;
      }
    });
    if (found) this.save();
    return found;
  }

  deleteModel(userId: string, modelId: string): boolean {
    const user = this.getUser(userId);
    const initialLen = user.models.length;
    user.models = user.models.filter(m => m.id !== modelId);
    if (user.models.length !== initialLen) {
      this.save();
      return true;
    }
    return false;
  }

  // Projects management
  getProjects(userId: string): Project[] {
    return this.getUser(userId).projects;
  }

  getProject(userId: string, projectId: string): Project | null {
    const user = this.getUser(userId);
    return user.projects.find(p => p.id === projectId) || null;
  }

  saveProject(userId: string, project: Partial<Project> & { name: string }): Project {
    const user = this.getUser(userId);
    const now = new Date().toISOString();

    if (project.id) {
      const idx = user.projects.findIndex(p => p.id === project.id);
      if (idx !== -1) {
        user.projects[idx] = {
          ...user.projects[idx],
          ...project,
          userId,
          updatedAt: now
        };
        this.save();
        return user.projects[idx];
      }
    }

    const newProject: Project = {
      id: `proj_${crypto.randomUUID().slice(0, 8)}`,
      userId,
      name: project.name,
      description: project.description || '',
      templateType: project.templateType || 'web',
      files: project.files || [
        {
          path: 'index.html',
          language: 'html',
          updatedAt: now,
          content: '<!DOCTYPE html>\n<html>\n<head><title>App</title></head>\n<body><h1>Hello AURA</h1></body>\n</html>'
        }
      ],
      activeFilePath: project.activeFilePath || 'index.html',
      createdAt: now,
      updatedAt: now
    };

    user.projects.unshift(newProject);
    this.save();
    return newProject;
  }

  deleteProject(userId: string, projectId: string): boolean {
    const user = this.getUser(userId);
    const initLen = user.projects.length;
    user.projects = user.projects.filter(p => p.id !== projectId);
    if (user.projects.length !== initLen) {
      this.save();
      return true;
    }
    return false;
  }

  // Chats management
  getChats(userId: string): ChatSession[] {
    return this.getUser(userId).chats;
  }

  getChat(userId: string, chatId: string): ChatSession | null {
    return this.getUser(userId).chats.find(c => c.id === chatId) || null;
  }

  saveChat(userId: string, chat: ChatSession): ChatSession {
    const user = this.getUser(userId);
    const idx = user.chats.findIndex(c => c.id === chat.id);
    if (idx !== -1) {
      user.chats[idx] = { ...chat, updatedAt: new Date().toISOString() };
    } else {
      user.chats.unshift(chat);
    }
    this.save();
    return chat;
  }

  deleteChat(userId: string, chatId: string): boolean {
    const user = this.getUser(userId);
    const initLen = user.chats.length;
    user.chats = user.chats.filter(c => c.id !== chatId);
    if (user.chats.length !== initLen) {
      this.save();
      return true;
    }
    return false;
  }

  // Agents
  getAgents(userId: string): Agent[] {
    return this.getUser(userId).agents;
  }

  saveAgent(userId: string, agent: Partial<Agent> & { name: string; systemPrompt: string }): Agent {
    const user = this.getUser(userId);
    const now = new Date().toISOString();

    if (agent.id) {
      const idx = user.agents.findIndex(a => a.id === agent.id);
      if (idx !== -1) {
        user.agents[idx] = {
          ...user.agents[idx],
          ...agent,
          userId,
          updatedAt: now
        } as Agent;
        this.save();
        return user.agents[idx];
      }
    }

    const newAgent: Agent = {
      id: `ag_${crypto.randomUUID().slice(0, 8)}`,
      userId,
      name: agent.name,
      description: agent.description || '',
      systemPrompt: agent.systemPrompt,
      providerId: agent.providerId || 'gemini',
      modelId: agent.modelId || 'gemini-2.5-flash',
      temperature: agent.temperature ?? 0.7,
      maxTokens: agent.maxTokens || 4096,
      tools: agent.tools || [],
      memoryEnabled: agent.memoryEnabled ?? true,
      createdAt: now,
      updatedAt: now
    };

    user.agents.unshift(newAgent);
    this.save();
    return newAgent;
  }

  deleteAgent(userId: string, agentId: string): boolean {
    const user = this.getUser(userId);
    const len = user.agents.length;
    user.agents = user.agents.filter(a => a.id !== agentId);
    if (user.agents.length !== len) {
      this.save();
      return true;
    }
    return false;
  }

  // Usage
  getUsage(userId: string): UsageLog[] {
    return this.getUser(userId).usage;
  }

  addUsageLog(userId: string, log: Omit<UsageLog, 'id' | 'timestamp' | 'userId'>): UsageLog {
    const user = this.getUser(userId);
    const newLog: UsageLog = {
      id: `us_${crypto.randomUUID().slice(0, 8)}`,
      userId,
      timestamp: new Date().toISOString(),
      ...log
    };
    user.usage.unshift(newLog);
    if (user.usage.length > 500) {
      user.usage = user.usage.slice(0, 500);
    }
    this.save();
    return newLog;
  }

  // Settings
  getSettings(userId: string): UserSettings {
    return this.getUser(userId).settings;
  }

  updateSettings(userId: string, settings: Partial<UserSettings>): UserSettings {
    const user = this.getUser(userId);
    user.settings = { ...user.settings, ...settings };
    this.save();
    return user.settings;
  }
}

export const auraStorage = new AuraStorage();
